apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    service: elasticsearch
status:
  loadBalancer: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: elasticsearch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/jogo-da-vida-paralelo-elk-network: "true"
        service: elasticsearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
          name: elasticsearch-tf
          ports:
            - containerPort: 9200
            - containerPort: 9300
          resources: {}
      restartPolicy: Always
status: {}
