apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: kafka-1
  name: kafka-1
spec:
  replicas: 3
  selector:
    matchLabels:
      service: kafka-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/jogo-da-vida-paralelo-default: "true"
        service: kafka-1
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://localhost:19092,PLAINTEXT_HOST://${PUBLIC_IP}:19093
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CREATE_TOPICS
              value: trab-final:3:3
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:19092,PLAINTEXT_HOST://localhost:19093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:22181,localhost:32181,localhost:42181
          image: confluentinc/cp-kafka:latest
          name: kafka-1
          resources: {}
      restartPolicy: Always
status: {}
