apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: kibana
  name: kibana
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    service: kibana
status:
  loadBalancer: {}


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kibana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/jogo-da-vida-paralelo-elk-network: "true"
        service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
          image: docker.elastic.co/kibana/kibana:7.10.2
          name: kibana-tf
          ports:
            - containerPort: 5601
          resources: {}
      restartPolicy: Always
status: {}
