apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: jogo-da-vida-paralelo-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/jogo-da-vida-paralelo-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/jogo-da-vida-paralelo-default: "true"

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: jogo-da-vida-paralelo-elk-network
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/jogo-da-vida-paralelo-elk-network: "true"
  podSelector:
    matchLabels:
      io.kompose.network/jogo-da-vida-paralelo-elk-network: "true"
