apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: zookeeper-1
  name: zookeeper-1
spec:
  replicas: 3
  selector:
    matchLabels:
      service: zookeeper-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/jogo-da-vida-paralelo-default: "true"
        service: zookeeper-1
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "22181"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SERVERS
              value: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: confluentinc/cp-zookeeper:latest
          name: zookeeper-1
          resources: {}
      restartPolicy: Always
status: {}
